version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: wine-catalog-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secure_password_change_me}
      MONGO_INITDB_DATABASE: wine_catalog
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - wine-catalog-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: wine-catalog-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secure_password_change_me}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin_change_me}
    depends_on:
      - mongodb
    networks:
      - wine-catalog-network

volumes:
  mongodb_data:

networks:
  wine-catalog-network:
    driver: bridge
