name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
      - 'package*.json'
  push:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests & Validation
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript type checking
      run: npx tsc --noEmit

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test

    - name: Generate test coverage
      run: npm run test -- --coverage
      env:
        NODE_ENV: test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./backend/coverage
        flags: backend
        name: backend-coverage

    - name: Check for security vulnerabilities
      run: npm audit --audit-level moderate

  security-scan:
    name: Security & Secret Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run secret detection
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified

    - name: Run CodeQL analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v3

  build-test:
    name: Build & Integration Test
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: testuser
          MONGO_INITDB_ROOT_PASSWORD: testpass
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Start backend server
      working-directory: ./backend
      run: |
        npm start &
        sleep 10
      env:
        NODE_ENV: production
        MONGODB_URI: mongodb://testuser:testpass@localhost:27017/wine-catalog-test?authSource=admin # secret-ignore
        JWT_SECRET: test-jwt-secret-for-ci-only # secret-ignore
        PORT: 3001

    - name: Health check
      run: |
        curl -f http://localhost:3001/api/health || exit 1

    - name: Run integration tests
      working-directory: ./backend
      run: npm test -- --testPathPattern="integration"
      env:
        NODE_ENV: test
        API_URL: http://localhost:3001

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Check for vulnerable dependencies
      working-directory: ./backend
      run: |
        npm audit --audit-level high
        npx audit-ci --high

    - name: Check for outdated dependencies
      working-directory: ./backend
      run: npm outdated || true

  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check commit messages
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: .commitlintrc.json

    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for breaking changes
      run: |
        git diff origin/main...HEAD --name-only | grep -E "(package\.json|tsconfig\.json|\.env\.example)" && echo "⚠️ Configuration files changed" || echo "✅ No config changes"

  validation-summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, security-scan, build-test, dependency-check]
    if: always()
    
    steps:
    - name: Check all jobs status
      run: |
        if [[ "${{ needs.backend-tests.result }}" == "success" && 
              "${{ needs.security-scan.result }}" == "success" && 
              "${{ needs.build-test.result }}" == "success" && 
              "${{ needs.dependency-check.result }}" == "success" ]]; then
          echo "✅ All validation checks passed!"
          exit 0
        else
          echo "❌ Some validation checks failed"
          echo "Backend Tests: ${{ needs.backend-tests.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"
          echo "Build Test: ${{ needs.build-test.result }}"
          echo "Dependency Check: ${{ needs.dependency-check.result }}"
          exit 1
        fi
