# DISABLED - Use secret-detection-simple.yml instead
# This workflow was causing BASE/HEAD commit issues
# 
# name: Secret Detection
# 
# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main, develop ]

jobs:
  secret-detection:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug Git Information
      run: |
        echo "Event: ${{ github.event_name }}"
        echo "Before: ${{ github.event.before }}"
        echo "After: ${{ github.sha }}"
        echo "Ref: ${{ github.ref }}"
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "PR Base: ${{ github.event.pull_request.base.sha }}"
          echo "PR Head: ${{ github.event.pull_request.head.sha }}"
        fi
        git log --oneline -3

    - name: Determine Scan Strategy
      id: scan-strategy
      run: |
        # Always use filesystem scan to avoid BASE/HEAD comparison issues
        echo "strategy=filesystem" >> $GITHUB_OUTPUT
        echo "scan-path=./" >> $GITHUB_OUTPUT
        
        # For PRs, we can still try to get the commit range for context
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "context=pr" >> $GITHUB_OUTPUT
          echo "pr-base=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "pr-head=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
        else
          echo "context=push" >> $GITHUB_OUTPUT
        fi

    - name: Run TruffleHog (Filesystem Scan)
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified --json --no-update

    - name: Run TruffleHog (Git History - Last 10 commits)
      continue-on-error: true
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified --json --no-update --since-commit=HEAD~10 --branch=HEAD

    - name: Upload scan results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trufflehog-results
        path: |
          trufflehog-results.json
        retention-days: 30

  comment-results:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: secret-detection
    if: github.event_name == 'pull_request' && always()
    
    steps:
    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const result = '${{ needs.secret-detection.result }}';
          
          let message = '';
          if (result === 'success') {
            message = `🔒 **Secret Detection: PASSED** ✅
            
            No secrets or credentials were detected in this PR.
            
            Scanned by TruffleHog with verified detectors only.`;
          } else {
            message = `🚨 **Secret Detection: FAILED** ❌
            
            **CRITICAL:** Potential secrets or credentials detected!
            
            ⚠️ **ACTION REQUIRED:**
            1. Review the workflow logs for details
            2. Remove any exposed secrets immediately
            3. Rotate any compromised credentials
            4. Use environment variables or secrets management
            
            **Common issues:**
            - API keys in code
            - Database credentials
            - Private keys or certificates
            - Authentication tokens
            
            Please fix these issues before merging.`;
          }
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: message
          });
